name: ramadhan_companion_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  add_2_calendar: ^3.0.1
  audioplayers: ^6.5.0
  carousel_slider: ^5.1.1
  cloud_firestore: ^6.0.1
  collection: ^1.19.1
  connectivity_plus: ^6.1.5
  date_format: ^2.0.9
  device_info_plus: ^11.5.0
  dotted_border: ^3.1.0
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  firebase_storage: ^13.0.2
  flutter:
    sdk: flutter
  flutter_compass: ^0.8.1
  flutter_image_compress: ^2.4.0
  flutter_inappwebview: ^6.1.5
  flutter_launcher_icons: ^0.14.4
  flutter_local_notifications: ^19.4.1
  flutter_map: ^8.2.2
  flutter_native_splash: ^2.4.6
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  google_fonts: ^6.3.0
  hijri: ^3.0.0
  hijri_calendar: ^1.0.7+7
  home_widget: ^0.8.0
  html: ^0.15.6
  http: ^1.5.0
  image_picker: ^1.2.0
  intl: ^0.20.2
  latlong2: ^0.9.1
  lottie: ^3.3.1
  provider: ^6.1.5
  pull_to_refresh: ^2.0.0
  quran: ^1.3.3
  quran_api: ^0.1.1
  scrollable_positioned_list: ^0.3.8
  share_plus: ^12.0.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1
  string_similarity: ^2.1.1
  table_calendar: ^3.2.0
  timezone: ^0.10.1
  # uni_links: ^0.5.1
  translator: ^1.0.4+1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/mosque_lottie.json
    - assets/icon/app_icon.jpg
    - assets/icon/masjid_icon.png
    - assets/icon/kaaba_icon.png
    - assets/icon/star_icon.png
    - assets/icon/islamic_calendar_icon.png
    - assets/icon/glitter_icon.png
    - assets/icon/quran_icon.png
    - assets/icon/donation_icon.png
    - assets/lottie/no_internet_lottie.json
    - assets/data/sadaqah.json
    - assets/icon/bookmark_empty_icon.png
    - assets/icon/bookmark_icon.png
    - assets/data/masjid_account.json
    - assets/icon/volume_icon.png
    - assets/icon/volume_outlined_icon.png
    - assets/icon/slider_filled_icon.png
    - assets/icon/hadith_icon.png
    - assets/icon/receipt_outlined_icon.png
    - assets/data/hadith_quran_sadaqah.json
    - assets/icon/ummah_app_logo.png
    - assets/icon/ummah-1-logo.png
    - assets/lottie/payment_failed_lottie.json
    - assets/lottie/payment_success_lottie.json
    - assets/icon/fpx_logo.png
    - assets/icon/debug_icon.png
    - assets/icon/performance_boost_icon.png
    - assets/icon/security_icon.png
    - assets/icon/update_icon.png
    - assets/mock_data/programme_1_mockup.jpg
    - assets/mock_data/programme_2_mockup.jpg
    - assets/mock_data/programme_3_mockup.jpg
    - assets/icon/share_outlined_icon.png
    - assets/icon/share_outlined_icon_1.png
    - assets/images/front-view-homeless-man-holding-cup-with-coins_23-2148760767_1_-removebg-preview.png
    - assets/lottie/reading_quran_lottie.json
    - assets/lottie/donate_lottie.json
    - assets/images/ummah_logo_transparent.png
    - assets/images/mosque_2_image.jpg
    - assets/icon/empty_data_icon.png
    - assets/images/fpx_logo.png
    - assets/audio/adhan_notification_cut.mp3
    - assets/icon/dua_icon.png
    - assets/icon/dua_1_icon.png

  fonts:
    - family: Liter
      fonts:
        - asset: assets/font/Liter-Regular.ttf
    - family: AmiriQuran
      fonts:
        - asset: assets/font/Amiri,Funnel_Display,Liter,Nunito_Sans,Open_Sans/Amiri/Amiri-Bold.ttf
    - family: Sans
      fonts:
        - asset: assets/font/SplineSans-VariableFont_wght.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/ummah-1-logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true
